version: '2'

services:
  workspace:
    build:
       context: ./Dockerfiles
       dockerfile: Dockerfile
    volumes:
      - ./www/:/var/www/html
      - ./vhost/:/var/www/vhosts
      - ./data/logs:/var/log/apache2
      - ./sites-available:/etc/apache2/sites-available
      - ./data/tmp:/tmp
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
      - ./Dockerfiles/config/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: muriwhenua
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  psql:
    image: mdillon/postgis
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  
  redis:
    image: redis:latest
    volumes:
      - data:/data
      
volumes:
  data:
    driver: local
  psql_data:
    driver: local